### PR TITLE
Updated (Daniel)'s README

### PR DESCRIPTION
**Pull request by aesthetetwo**
Yusuf please review and approve my pull request.

### CODE REVIEW

**Review by YusufBolden — CHANGES_REQUESTED** [review]
Great job! Update your README.md by adding 2-3 more lines to it and then go through the steps to push to the repo and submit another pull request

**Comment by aesthetetwo** [comment]
will do.

**Review by YusufBolden — APPROVED** [review]
I don't see any changes to your README. Did you forget to push them to the repo?

**Comment by aesthetetwo** [comment]
Haven't done it yet. Will attempt no later than today or tomorrow by the
end of day.

**Pull request merged**
